--CREATE DATABASE Sehirler_DB
--GO
--USE Sehirler_DB
--GO
--CREATE TABLE Sehirler
--(
--	SehirID INT IDENTITY(1,1),
--	Isim NVARCHAR(100) NOT NULL,
--	CONSTRAINT pk_sehir PRIMARY KEY(SehirID)
--)
--GO
--CREATE TABLE Ilceler
--(
--	IlceID INT IDENTITY(1,1),
--	SehirID INT NOT NULL,
--	Isim NVARCHAR(100) NOT NULL,
--	CONSTRAINT pk_ilce PRIMARY KEY(IlceID),
--	CONSTRAINT fk_ilcesehir FOREIGN KEY(SehirID) REFERENCES Sehirler(SehirID),
--)
INSERT Sehirler (Isim) VALUES ('Adana')
INSERT Sehirler (Isim) VALUES ('Adýyaman')
INSERT Sehirler (Isim) VALUES ('Afyonkarahisar')
INSERT Sehirler (Isim) VALUES ('Aðrý')
INSERT Sehirler (Isim) VALUES ('Amasya')
INSERT Sehirler (Isim) VALUES ('Ankara')
INSERT Sehirler (Isim) VALUES ('Antalya')
INSERT Sehirler (Isim) VALUES ('Artvin')
INSERT Sehirler (Isim) VALUES ('Aydýn')
INSERT Sehirler (Isim) VALUES ('Balýkesir')
INSERT Sehirler (Isim) VALUES ('Bilecik')
INSERT Sehirler (Isim) VALUES ('Bingöl')
INSERT Sehirler (Isim) VALUES ('Bitlis')
INSERT Sehirler (Isim) VALUES ('Bolu')
INSERT Sehirler (Isim) VALUES ('Burdur')
INSERT Sehirler (Isim) VALUES ('Bursa')
INSERT Sehirler (Isim) VALUES ('Çanakkale')
INSERT Sehirler (Isim) VALUES ('Çankýrý')
INSERT Sehirler (Isim) VALUES ('Çorum')
INSERT Sehirler (Isim) VALUES ('Denizli')
INSERT Sehirler (Isim) VALUES ('Diyarbakýr')
INSERT Sehirler (Isim) VALUES ('Edirne')
INSERT Sehirler (Isim) VALUES ('Elazýð')
INSERT Sehirler (Isim) VALUES ('Erzincan')
INSERT Sehirler (Isim) VALUES ('Erzurum')
INSERT Sehirler (Isim) VALUES ('Eskiþehir')
INSERT Sehirler (Isim) VALUES ('Gaziantep')
INSERT Sehirler (Isim) VALUES ('Giresun')
INSERT Sehirler (Isim) VALUES ('Gümüþhane')
INSERT Sehirler (Isim) VALUES ('Hakkari')
INSERT Sehirler (Isim) VALUES ('Hatay')
INSERT Sehirler (Isim) VALUES ('Isparta')
INSERT Sehirler (Isim) VALUES ('Mersin(Ýçel)')
INSERT Sehirler (Isim) VALUES ('Ýstanbul')
INSERT Sehirler (Isim) VALUES ('Ýzmir')
INSERT Sehirler (Isim) VALUES ('Kars')
INSERT Sehirler (Isim) VALUES ('Kastamonu')
INSERT Sehirler (Isim) VALUES ('Kayseri')
INSERT Sehirler (Isim) VALUES ('Kýrklareli')
INSERT Sehirler (Isim) VALUES ('Kýrþehir')
INSERT Sehirler (Isim) VALUES ('Kocaeli')
INSERT Sehirler (Isim) VALUES ('Kahramanmaraþ')
INSERT Sehirler (Isim) VALUES ('Konya')
INSERT Sehirler (Isim) VALUES ('Kütahya')
INSERT Sehirler (Isim) VALUES ('Malatya')
INSERT Sehirler (Isim) VALUES ('Manisa')
INSERT Sehirler (Isim) VALUES ('Mardin')
INSERT Sehirler (Isim) VALUES ('Muðla')
INSERT Sehirler (Isim) VALUES ('Muþ')
INSERT Sehirler (Isim) VALUES ('Nevþehir')
INSERT Sehirler (Isim) VALUES ('Niðde')
INSERT Sehirler (Isim) VALUES ('Ordu')
INSERT Sehirler (Isim) VALUES ('Rize')
INSERT Sehirler (Isim) VALUES ('Sakarya')
INSERT Sehirler (Isim) VALUES ('Samsun')
INSERT Sehirler (Isim) VALUES ('Siirt')
INSERT Sehirler (Isim) VALUES ('Sinop')
INSERT Sehirler (Isim) VALUES ('Sivas')
INSERT Sehirler (Isim) VALUES ('Tekirdað')
INSERT Sehirler (Isim) VALUES ('Tokat')
INSERT Sehirler (Isim) VALUES ('Trabzon')
INSERT Sehirler (Isim) VALUES ('Tunceli')
INSERT Sehirler (Isim) VALUES ('Þanlýurfa')
INSERT Sehirler (Isim) VALUES ('Uþak')
INSERT Sehirler (Isim) VALUES ('Van')
INSERT Sehirler (Isim) VALUES ('Yozgat')
INSERT Sehirler (Isim) VALUES ('Zonguldak')
INSERT Sehirler (Isim) VALUES ('Aksaray')
INSERT Sehirler (Isim) VALUES ('Bayburt')
INSERT Sehirler (Isim) VALUES ('Karaman')
INSERT Sehirler (Isim) VALUES ('Kýrýkkale')
INSERT Sehirler (Isim) VALUES ('Batman')
INSERT Sehirler (Isim) VALUES ('Þýrnak')
INSERT Sehirler (Isim) VALUES ('Bartýn')
INSERT Sehirler (Isim) VALUES ('Ardahan')
INSERT Sehirler (Isim) VALUES ('Iðdýr')
INSERT Sehirler (Isim) VALUES ('Yalova')
INSERT Sehirler (Isim) VALUES ('Karabük')
INSERT Sehirler (Isim) VALUES ('Kilis')
INSERT Sehirler (Isim) VALUES ('Osmaniye')
INSERT Sehirler (Isim) VALUES ('Düzce')

INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'ALADAÐ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'CEYHAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'ÇUKUROVA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'FEKE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'ÝMAMOÐLU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'KARAÝSALI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'KARATAÞ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'KOZAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'POZANTI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'SAÝMBEYLÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'SARIÇAM')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'SEYHAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'TUFANBEYLÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'YUMURTALIK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(1,'YÜREÐÝR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'BESNÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'ÇELÝKHAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'GERGER')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'GÖLBAÞI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'KAHTA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'SAMSAT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'SÝNCÝK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(2,'TUT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'BAÞMAKÇI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'BAYAT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'BOLVADÝN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'ÇAY')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'ÇOBANLAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'DAZKIRI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'DÝNAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'EMÝRDAÐ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'EVCÝLER')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'HOCALAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'ÝHSANÝYE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'ÝSCEHÝSAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'KIZILÖREN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'SANDIKLI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'SÝNANPAÞA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'SULTANDAÐI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(3,'ÞUHUT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'DÝYADÝN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'DOÐUBAYAZIT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'ELEÞKÝRT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'HAMUR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'PATNOS')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'TAÞLIÇAY')
INSERT INTO Ilceler(SehirID,Isim) VALUES(4,'TUTAK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(5,'GÖYNÜCEK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(5,'GÜMÜÞHACIKÖY')
INSERT INTO Ilceler(SehirID,Isim) VALUES(5,'HAMAMÖZÜ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(5,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(5,'MERZÝFON')
INSERT INTO Ilceler(SehirID,Isim) VALUES(5,'SULUOVA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(5,'TAÞOVA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'AKYURT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'ALTINDAÐ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'AYAÞ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'BALA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'BEYPAZARI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'ÇAMLIDERE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'ÇANKAYA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'ÇUBUK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'ELMADAÐ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'ETÝMESGUT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'EVREN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'GÖLBAÞI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'GÜDÜL')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'HAYMANA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'KAHRAMANKAZAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'KALECÝK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'KEÇÝÖREN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'KIZILCAHAMAM')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'MAMAK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'NALLIHAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'POLATLI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'PURSAKLAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'SÝNCAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'ÞEREFLÝKOÇHÝSAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(6,'YENÝMAHALLE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'AKSEKÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'AKSU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'ALANYA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'DEMRE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'DÖÞEMEALTI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'ELMALI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'FÝNÝKE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'GAZÝPAÞA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'GÜNDOÐMUÞ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'ÝBRADI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'KAÞ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'KEMER')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'KEPEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'KONYAALTI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'KORKUTELÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'KUMLUCA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'MANAVGAT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'MURATPAÞA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(7,'SERÝK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'ARDANUÇ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'ARHAVÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'BORÇKA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'HOPA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'KEMALPAÞA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'MURGUL')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'ÞAVÞAT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(8,'YUSUFELÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'BOZDOÐAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'BUHARKENT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'ÇÝNE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'DÝDÝM')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'EFELER')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'GERMENCÝK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'ÝNCÝRLÝOVA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'KARACASU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'KARPUZLU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'KOÇARLI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'KÖÞK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'KUÞADASI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'KUYUCAK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'NAZÝLLÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'SÖKE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'SULTANHÝSAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(9,'YENÝPAZAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'ALTIEYLÜL')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'AYVALIK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'BALYA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'BANDIRMA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'BÝGADÝÇ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'BURHANÝYE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'DURSUNBEY')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'EDREMÝT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'ERDEK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'GÖMEÇ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'GÖNEN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'HAVRAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'ÝVRÝNDÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'KARESÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'KEPSUT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'MANYAS')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'MARMARA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'SAVAÞTEPE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'SINDIRGI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(10,'SUSURLUK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'BOZÜYÜK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'GÖLPAZARI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'ÝNHÝSAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'OSMANELÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'PAZARYERÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'SÖÐÜT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(11,'YENÝPAZAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'ADAKLI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'GENÇ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'KARLIOVA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'KÝÐI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'SOLHAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'YAYLADERE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(12,'YEDÝSU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(13,'ADÝLCEVAZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(13,'AHLAT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(13,'GÜROYMAK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(13,'HÝZAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(13,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(13,'MUTKÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(13,'TATVAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'DÖRTDÝVAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'GEREDE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'GÖYNÜK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'KIBRISCIK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'MENGEN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'MUDURNU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'SEBEN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(14,'YENÝÇAÐA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'AÐLASUN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'ALTINYAYLA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'BUCAK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'ÇAVDIR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'ÇELTÝKÇÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'GÖLHÝSAR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'KARAMANLI')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'KEMER')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'TEFENNÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(15,'YEÞÝLOVA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'BÜYÜKORHAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'GEMLÝK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'GÜRSU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'HARMANCIK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'ÝNEGÖL')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'ÝZNÝK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'KARACABEY')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'KELES')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'KESTEL')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'MUDANYA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'MUSTAFAKEMALPAÞA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'NÝLÜFER')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'ORHANELÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'ORHANGAZÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'OSMANGAZÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'YENÝÞEHÝR')
INSERT INTO Ilceler(SehirID,Isim) VALUES(16,'YILDIRIM')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'AYVACIK')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'BAYRAMÝÇ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'BÝGA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'BOZCAADA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'ÇAN')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'ECEABAT')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'EZÝNE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'GELÝBOLU')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'GÖKÇEADA')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'LAPSEKÝ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'MERKEZ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(17,'YENÝCE')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Çankýrý Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Çerkeþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Eldivan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Ilgaz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Kurþunlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Orta')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Þabanözü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Yapraklý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Atkaracalar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Kýzýlýrmak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Bayramören')
INSERT INTO Ilceler(SehirID,Isim) VALUES(18,'Korgun')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Alaca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Bayat / Çorum')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Çorum Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Ýskilip')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Kargý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Mecitözü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Ortaköy / Çorum')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Osmancýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Sungurlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Boðazkale')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Uðurludað')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Dodurga')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Laçin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(19,'Oðuzlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Acýpayam')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Buldan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Çal')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Çameli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Çardak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Çivril')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Güney')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Kale / Denizli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Sarayköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Tavas')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Babadað')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Bekilli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Honaz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Serinhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Pamukkale')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Baklan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Beyaðaç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Bozkurt / Denizli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(20,'Merkezefendi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Bismil')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Çermik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Çýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Çüngüþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Dicle')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Ergani')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Hani')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Hazro')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Kulp')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Lice')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Silvan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Eðil')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Kocaköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Baðlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Kayapýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Sur')
INSERT INTO Ilceler(SehirID,Isim) VALUES(21,'Yeniþehir / Diyarbakýr')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Edirne Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Enez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Havsa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Ýpsala')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Keþan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Lalapaþa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Meriç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Uzunköprü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(22,'Süloðlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Aðýn')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Baskil')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Elazýð Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Karakoçan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Keban')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Maden')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Palu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Sivrice')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Arýcak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Kovancýlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(23,'Alacakaya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Çayýrlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Erzincan Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Ýliç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Kemah')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Kemaliye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Refahiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Tercan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Üzümlü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(24,'Otlukbeli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Aþkale')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Çat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Hýnýs')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Horasan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Ýspir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Karayazý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Narman')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Oltu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Olur')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Pasinler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Þenkaya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Tekman')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Tortum')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Karaçoban')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Uzundere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Pazaryolu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Aziziye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Köprüköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Palandöken')
INSERT INTO Ilceler(SehirID,Isim) VALUES(25,'Yakutiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Çifteler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Mahmudiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Mihalýççýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Sarýcakaya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Seyitgazi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Sivrihisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Alpu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Beylikova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Ýnönü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Günyüzü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Han')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Mihalgazi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Odunpazarý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(26,'Tepebaþý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Araban')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Ýslahiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Nizip')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Oðuzeli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Yavuzeli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Þahinbey')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Þehitkamil')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Karkamýþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(27,'Nurdaðý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Alucra')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Bulancak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Dereli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Espiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Eynesil')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Giresun Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Görele')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Keþap')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Þebinkarahisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Tirebolu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Piraziz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Yaðlýdere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Çamoluk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Çanakçý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Doðankent')
INSERT INTO Ilceler(SehirID,Isim) VALUES(28,'Güce')
INSERT INTO Ilceler(SehirID,Isim) VALUES(29,'Gümüþhane Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(29,'Kelkit')
INSERT INTO Ilceler(SehirID,Isim) VALUES(29,'Þiran')
INSERT INTO Ilceler(SehirID,Isim) VALUES(29,'Torul')
INSERT INTO Ilceler(SehirID,Isim) VALUES(29,'Köse')
INSERT INTO Ilceler(SehirID,Isim) VALUES(29,'Kürtün')
INSERT INTO Ilceler(SehirID,Isim) VALUES(30,'Çukurca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(30,'Hakkari Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(30,'Þemdinli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(30,'Yüksekova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Altýnözü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Dörtyol')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Hassa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Ýskenderun')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Kýrýkhan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Reyhanlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Samandað')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Yayladaðý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Erzin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Belen')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Kumlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Antakya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Arsuz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Defne')
INSERT INTO Ilceler(SehirID,Isim) VALUES(31,'Payas')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Atabey')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Eðirdir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Gelendost')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Isparta Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Keçiborlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Senirkent')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Sütçüler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Þarkikaraaðaç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Uluborlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Yalvaç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Aksu / Isparta')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Gönen / Isparta')
INSERT INTO Ilceler(SehirID,Isim) VALUES(32,'Yeniþarbademli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Anamur')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Erdemli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Gülnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Mut')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Silifke')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Tarsus')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Aydýncýk / Mersin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Bozyazý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Çamlýyayla')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Akdeniz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Mezitli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Toroslar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(33,'Yeniþehir / Mersin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Adalar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Bakýrköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Beþiktaþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Beykoz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Beyoðlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Çatalca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Eyüp')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Fatih')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Gaziosmanpaþa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Kadýköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Kartal')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Sarýyer')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Silivri')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Þile')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Þiþli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Üsküdar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Zeytinburnu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Büyükçekmece')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Kaðýthane')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Küçükçekmece')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Pendik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Ümraniye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Bayrampaþa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Avcýlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Baðcýlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Bahçelievler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Güngören')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Maltepe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Sultanbeyli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Tuzla')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Esenler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Arnavutköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Ataþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Baþakþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Beylikdüzü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Çekmeköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Esenyurt')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Sancaktepe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(34,'Sultangazi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Aliaða')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Bayýndýr')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Bergama')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Bornova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Çeþme')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Dikili')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Foça')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Karaburun')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Karþýyaka')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Kemalpaþa / Ýzmir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Kýnýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Kiraz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Menemen')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Ödemiþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Seferihisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Selçuk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Tire')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Torbalý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Urla')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Beydað')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Buca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Konak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Menderes')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Balçova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Çiðli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Gaziemir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Narlýdere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Güzelbahçe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Bayraklý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(35,'Karabaðlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Arpaçay')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Digor')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Kaðýzman')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Kars Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Sarýkamýþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Selim')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Susuz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(36,'Akyaka')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Abana')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Araç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Azdavay')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Bozkurt / Kastamonu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Cide')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Çatalzeytin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Daday')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Devrekani')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Ýnebolu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Kastamonu Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Küre')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Taþköprü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Tosya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Ýhsangazi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Pýnarbaþý / Kastamonu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Þenpazar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Aðlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Doðanyurt')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Hanönü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(37,'Seydiler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Bünyan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Develi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Felahiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Ýncesu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Pýnarbaþý / Kayseri')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Sarýoðlan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Sarýz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Tomarza')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Yahyalý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Yeþilhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Akkýþla')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Talas')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Kocasinan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Melikgazi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Hacýlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(38,'Özvatan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Babaeski')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Demirköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Kýrklareli Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Kofçaz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Lüleburgaz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Pehlivanköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Pýnarhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(39,'Vize')
INSERT INTO Ilceler(SehirID,Isim) VALUES(40,'Çiçekdaðý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(40,'Kaman')
INSERT INTO Ilceler(SehirID,Isim) VALUES(40,'Kýrþehir Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(40,'Mucur')
INSERT INTO Ilceler(SehirID,Isim) VALUES(40,'Akpýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(40,'Akçakent')
INSERT INTO Ilceler(SehirID,Isim) VALUES(40,'Boztepe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Gebze')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Gölcük')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Kandýra')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Karamürsel')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Körfez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Derince')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Baþiskele')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Çayýrova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Darýca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Dilovasý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Ýzmit')
INSERT INTO Ilceler(SehirID,Isim) VALUES(41,'Kartepe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Akþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Beyþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Bozkýr')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Cihanbeyli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Çumra')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Doðanhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Ereðli / Konya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Hadim')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Ilgýn')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Kadýnhaný')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Karapýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Kulu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Sarayönü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Seydiþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Yunak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Akören')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Altýnekin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Derebucak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Hüyük')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Karatay')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Meram')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Selçuklu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Taþkent')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Ahýrlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Çeltik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Derbent')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Emirgazi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Güneysýnýr')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Halkapýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Tuzlukçu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(42,'Yalýhüyük')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Altýntaþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Domaniç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Emet')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Gediz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Kütahya Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Simav')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Tavþanlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Aslanapa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Dumlupýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Hisarcýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Þaphane')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Çavdarhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(43,'Pazarlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Akçadað')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Arapgir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Arguvan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Darende')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Doðanþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Hekimhan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Pütürge')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Yeþilyurt / Malatya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Battalgazi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Doðanyol')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Kale / Malatya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Kuluncak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(44,'Yazýhan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Akhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Alaþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Demirci')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Gördes')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Kýrkaðaç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Kula')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Salihli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Sarýgöl')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Saruhanlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Selendi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Soma')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Turgutlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Ahmetli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Gölmarmara')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Köprübaþý / Manisa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Þehzadeler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(45,'Yunusemre')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Afþin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Andýrýn')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Elbistan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Göksun')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Pazarcýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Türkoðlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Çaðlayancerit')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Ekinözü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Nurhak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Dulkadiroðlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(46,'Onikiþubat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Derik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Kýzýltepe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Mazýdaðý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Midyat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Nusaybin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Ömerli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Savur')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Dargeçit')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Yeþilli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(47,'Artuklu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Bodrum')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Datça')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Fethiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Köyceðiz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Marmaris')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Milas')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Ula')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Yataðan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Dalaman')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Ortaca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Kavaklýdere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Menteþe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(48,'Seydikemer')
INSERT INTO Ilceler(SehirID,Isim) VALUES(49,'Bulanýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(49,'Malazgirt')
INSERT INTO Ilceler(SehirID,Isim) VALUES(49,'Muþ Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(49,'Varto')
INSERT INTO Ilceler(SehirID,Isim) VALUES(49,'Hasköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(49,'Korkut')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Avanos')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Derinkuyu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Gülþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Hacýbektaþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Kozaklý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Nevþehir Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Ürgüp')
INSERT INTO Ilceler(SehirID,Isim) VALUES(50,'Acýgöl')
INSERT INTO Ilceler(SehirID,Isim) VALUES(51,'Bor')
INSERT INTO Ilceler(SehirID,Isim) VALUES(51,'Çamardý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(51,'Niðde Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(51,'Ulukýþla')
INSERT INTO Ilceler(SehirID,Isim) VALUES(51,'Altunhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(51,'Çiftlik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Akkuþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Aybastý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Fatsa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Gölköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Korgan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Kumru')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Mesudiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Perþembe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Ulubey / Ordu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Ünye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Gülyalý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Gürgentepe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Çamaþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Çatalpýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Çaybaþý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Ýkizce')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Kabadüz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Kabataþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(52,'Altýnordu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Ardeþen')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Çamlýhemþin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Çayeli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Fýndýklý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Ýkizdere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Kalkandere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Pazar / Rize')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Rize Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Güneysu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Derepazarý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Hemþin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(53,'Ýyidere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Akyazý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Geyve')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Hendek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Karasu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Kaynarca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Sapanca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Kocaali')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Pamukova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Taraklý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Ferizli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Karapürçek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Söðütlü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Adapazarý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Arifiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Erenler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(54,'Serdivan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Alaçam')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Bafra')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Çarþamba')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Havza')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Kavak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Ladik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Terme')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Vezirköprü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Asarcýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'44700')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Salýpazarý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Tekkeköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Ayvacýk / Samsun')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Yakakent')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Atakum')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Canik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(55,'Ýlkadým')
INSERT INTO Ilceler(SehirID,Isim) VALUES(56,'Baykan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(56,'Eruh')
INSERT INTO Ilceler(SehirID,Isim) VALUES(56,'Kurtalan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(56,'Pervari')
INSERT INTO Ilceler(SehirID,Isim) VALUES(56,'Siirt Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(56,'Þirvan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(56,'Tillo')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Ayancýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Boyabat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Duraðan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Erfelek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Gerze')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Sinop Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Türkeli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Dikmen')
INSERT INTO Ilceler(SehirID,Isim) VALUES(57,'Saraydüzü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Divriði')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Gemerek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Gürün')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Hafik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Ýmranlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Kangal')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Koyulhisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Sivas Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Suþehri')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Þarkýþla')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Yýldýzeli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Zara')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Akýncýlar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Altýnyayla / Sivas')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Doðanþar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Gölova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(58,'Ulaþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Çerkezköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Çorlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Hayrabolu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Malkara')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Muratlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Saray / Tekirdað')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Þarköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Marmaraereðlisi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Ergene')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Kapaklý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(59,'Süleymanpaþa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Almus')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Artova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Erbaa')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Niksar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Reþadiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Tokat Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Turhal')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Zile')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Pazar / Tokat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Yeþilyurt / Tokat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Baþçiftlik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(60,'Sulusaray')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Akçaabat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Araklý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Arsin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Çaykara')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Maçka')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Of')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Sürmene')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Tonya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Vakfýkebir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Yomra')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Beþikdüzü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Þalpazarý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Çarþýbaþý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Dernekpazarý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Düzköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Hayrat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Köprübaþý / Trabzon')
INSERT INTO Ilceler(SehirID,Isim) VALUES(61,'Ortahisar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Çemiþgezek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Hozat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Mazgirt')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Nazýmiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Ovacýk / Tunceli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Pertek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Pülümür')
INSERT INTO Ilceler(SehirID,Isim) VALUES(62,'Tunceli Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Akçakale')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Birecik')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Bozova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Ceylanpýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Halfeti')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Hilvan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Siverek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Suruç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Viranþehir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Harran')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Eyyübiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Haliliye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(63,'Karaköprü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(64,'Banaz')
INSERT INTO Ilceler(SehirID,Isim) VALUES(64,'Eþme')
INSERT INTO Ilceler(SehirID,Isim) VALUES(64,'Karahallý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(64,'Sivaslý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(64,'Ulubey / Uþak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(64,'Uþak Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Baþkale')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Çatak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Erciþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Gevaþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Gürpýnar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Muradiye')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Özalp')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Bahçesaray')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Çaldýran')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Edremit / Van')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Saray / Van')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Ýpekyolu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(65,'Tuþba')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Akdaðmadeni')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Boðazlýyan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Çayýralan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Çekerek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Sarýkaya')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Sorgun')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Þefaatli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Yerköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Yozgat Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Aydýncýk / Yozgat')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Çandýr')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Kadýþehri')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Saraykent')
INSERT INTO Ilceler(SehirID,Isim) VALUES(66,'Yenifakýlý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Çaycuma')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Devrek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Ereðli / Zonguldak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Zonguldak Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Alaplý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Gökçebey')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Kilimli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(67,'Kozlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(68,'Aksaray Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(68,'Ortaköy / Aksaray')
INSERT INTO Ilceler(SehirID,Isim) VALUES(68,'Aðaçören')
INSERT INTO Ilceler(SehirID,Isim) VALUES(68,'Güzelyurt')
INSERT INTO Ilceler(SehirID,Isim) VALUES(68,'Sarýyahþi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(68,'Eskil')
INSERT INTO Ilceler(SehirID,Isim) VALUES(68,'Gülaðaç')
INSERT INTO Ilceler(SehirID,Isim) VALUES(69,'Bayburt Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(69,'Aydýntepe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(69,'Demirözü')
INSERT INTO Ilceler(SehirID,Isim) VALUES(70,'Ermenek')
INSERT INTO Ilceler(SehirID,Isim) VALUES(70,'Karaman Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(70,'Ayrancý')
INSERT INTO Ilceler(SehirID,Isim) VALUES(70,'Kazýmkarabekir')
INSERT INTO Ilceler(SehirID,Isim) VALUES(70,'Baþyayla')
INSERT INTO Ilceler(SehirID,Isim) VALUES(70,'Sarýveliler')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Delice')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Keskin')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Kýrýkkale Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Sulakyurt')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Bahþili')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Balýþeyh')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Çelebi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Karakeçili')
INSERT INTO Ilceler(SehirID,Isim) VALUES(71,'Yahþihan')
INSERT INTO Ilceler(SehirID,Isim) VALUES(72,'Batman Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(72,'Beþiri')
INSERT INTO Ilceler(SehirID,Isim) VALUES(72,'Gercüþ')
INSERT INTO Ilceler(SehirID,Isim) VALUES(72,'Kozluk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(72,'Sason')
INSERT INTO Ilceler(SehirID,Isim) VALUES(72,'Hasankeyf')
INSERT INTO Ilceler(SehirID,Isim) VALUES(73,'Beytüþþebap')
INSERT INTO Ilceler(SehirID,Isim) VALUES(73,'Cizre')
INSERT INTO Ilceler(SehirID,Isim) VALUES(73,'Ýdil')
INSERT INTO Ilceler(SehirID,Isim) VALUES(73,'Silopi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(73,'Þýrnak Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(73,'Uludere')
INSERT INTO Ilceler(SehirID,Isim) VALUES(73,'Güçlükonak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(74,'Bartýn Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(74,'Kurucaþile')
INSERT INTO Ilceler(SehirID,Isim) VALUES(74,'Ulus')
INSERT INTO Ilceler(SehirID,Isim) VALUES(74,'Amasra')
INSERT INTO Ilceler(SehirID,Isim) VALUES(75,'Ardahan Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(75,'Çýldýr')
INSERT INTO Ilceler(SehirID,Isim) VALUES(75,'Göle')
INSERT INTO Ilceler(SehirID,Isim) VALUES(75,'Hanak')
INSERT INTO Ilceler(SehirID,Isim) VALUES(75,'Posof')
INSERT INTO Ilceler(SehirID,Isim) VALUES(75,'Damal')
INSERT INTO Ilceler(SehirID,Isim) VALUES(76,'Aralýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(76,'Iðdýr Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(76,'Tuzluca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(76,'Karakoyunlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(77,'Yalova Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(77,'Altýnova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(77,'Armutlu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(77,'Çýnarcýk')
INSERT INTO Ilceler(SehirID,Isim) VALUES(77,'Çiftlikköy')
INSERT INTO Ilceler(SehirID,Isim) VALUES(77,'Termal')
INSERT INTO Ilceler(SehirID,Isim) VALUES(78,'Eflani')
INSERT INTO Ilceler(SehirID,Isim) VALUES(78,'Eskipazar')
INSERT INTO Ilceler(SehirID,Isim) VALUES(78,'Karabük Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(78,'Ovacýk / Karabük')
INSERT INTO Ilceler(SehirID,Isim) VALUES(78,'Safranbolu')
INSERT INTO Ilceler(SehirID,Isim) VALUES(78,'Yenice / Karabük')
INSERT INTO Ilceler(SehirID,Isim) VALUES(79,'Kilis Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(79,'Elbeyli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(79,'Musabeyli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(79,'Polateli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(80,'Bahçe')
INSERT INTO Ilceler(SehirID,Isim) VALUES(80,'Kadirli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(80,'Osmaniye Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(80,'Düziçi')
INSERT INTO Ilceler(SehirID,Isim) VALUES(80,'Hasanbeyli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(80,'Sumbas')
INSERT INTO Ilceler(SehirID,Isim) VALUES(80,'Toprakkale')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Akçakoca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Düzce Merkez')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Yýðýlca')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Cumayeri')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Gölyaka')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Çilimli')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Gümüþova')
INSERT INTO Ilceler(SehirID,Isim) VALUES(81,'Kaynaþlý')

